server:
  default:
    port: 8088
    readTimeout: 30
    writeTimeout: 30
    idleTimeout: 90
    maxHeaderBytes: 1048576
    allowOrigins: "*"

logger:
  level: info

database:
  mongo:
    host: localhost
    port: 27017
    name: waftester
    username: {{ .MONGO_USER }}
    password: {{ .MONGO_PASSWORD}}
